### ISSUE TITLE
Cannot alter settings

### ISSUE THREAD

**Issue by StavromulaBeta** [siefkenj/MailMergeP#61]
Hi, I'm using Thunderbird 128.3.0esr with MailMergeP and I'm unable to alter any of the settings in the settings window. Changing any of them causes them to be altered momentarily before returning to their original values.

**Comment by siefkenj** [comment]
Thank you for the report. Currently my system is on TB115. When TB128 is available to me, I will investigate this issue.

**Comment by StavromulaBeta** [comment]
Hi again - it turns out that the settings can be altered but only if there isn't a spreadsheet loaded. If I then load one they persist.

**Comment by ws333** [comment]
I have the same issue when trying to change any values on the Settings page when a spreadsheet is loaded.
Using TB 128.6.0esr (64-bit) on macOS Ventura 13.7.2

Can confirm that settings can be changed when no spreadsheet is loaded.

Looking into it as it seems to be caused by cloning an object containing a function, see error from browser simulation below. 


This is the message in the error console in TB:


```
Uncaught (in promise) DOMException: Function object could not be cloned.
    r0 moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:50
    r0 moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:50
    updatePref moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:130
    Noe moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:50
    p moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:50
    wY moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:40
    joe moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:50
    f moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:50
    n moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:351
    Jne moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    eie moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    tie moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    PI moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    tz moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    y8 moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    qE moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:40
    EW moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    y8 moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    xE moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    mie moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
index.js:50
    f moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:50
    (Async: promise callback)
    f moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:50
    n moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:351
    Jne moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    eie moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    tie moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    PI moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    tz moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    y8 moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    qE moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:40
    EW moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    y8 moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    xE moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    mie moz-extension://f9e497cd-fa0c-46ab-a4c0-26ca6f9f96d3/content/interface/assets/index.js:37
    receiveMessage resource://gre/actors/SelectChild.sys.mjs:256
    receiveMessage resource://gre/actors/SelectChild.sys.mjs:494
```

This is the error message in browser simulation:

```
service.js:47 Uncaught (in promise) DataCloneError: Failed to execute 'postMessage' on 'Window': function td(e,t){var r="",n,i,a=[],o,s,l,u;switch(t){case"dbcs":if(u=this.l,Lt&&Buffer.isBuffer(this))r=this.sl...<omitted>...r} could not be cloned.
    at service.js:47:16
    at new Promise (<anonymous>)
    at r0 (service.js:32:12)
    at async model.js:35:13
(anonymous) @ service.js:47
r0 @ service.js:32
await in r0
(anonymous) @ model.js:35
(anonymous) @ easy-peasy.esm.js:713
(anonymous) @ easy-peasy.esm.js:762
(anonymous) @ index.js:8
(anonymous) @ easy-peasy.esm.js:877
f @ easy-peasy.esm.js:761
(anonymous) @ settings-tab.jsx:14
Jne @ react-dom.production.min.js:54
eie @ react-dom.production.min.js:54
tie @ react-dom.production.min.js:55
PI @ react-dom.production.min.js:105
tz @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
qE @ react-dom.production.min.js:274
EW @ react-dom.production.min.js:52
y8 @ react-dom.production.min.js:109
xE @ react-dom.production.min.js:74
mie @ react-dom.production.min.js:73
```
